// Generated by rstantools.  Do not edit by hand.

/*
    nafm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    nafm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with nafm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_nmr_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 50> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 18, column 2 to column 14)",
  " (in 'string', line 19, column 2 to column 22)",
  " (in 'string', line 20, column 2 to column 18)",
  " (in 'string', line 21, column 2 to column 23)",
  " (in 'string', line 22, column 2 to column 32)",
  " (in 'string', line 25, column 2 to column 32)",
  " (in 'string', line 26, column 2 to column 23)",
  " (in 'string', line 27, column 2 to column 64)",
  " (in 'string', line 30, column 9 to column 10)",
  " (in 'string', line 30, column 2 to column 23)",
  " (in 'string', line 32, column 4 to column 46)",
  " (in 'string', line 31, column 17 to line 33, column 3)",
  " (in 'string', line 31, column 2 to line 33, column 3)",
  " (in 'string', line 35, column 2 to column 36)",
  " (in 'string', line 36, column 2 to column 31)",
  " (in 'string', line 37, column 2 to column 33)",
  " (in 'string', line 38, column 2 to column 37)",
  " (in 'string', line 39, column 2 to column 32)",
  " (in 'string', line 40, column 2 to column 24)",
  " (in 'string', line 2, column 2 to column 17)",
  " (in 'string', line 3, column 9 to column 10)",
  " (in 'string', line 3, column 2 to column 14)",
  " (in 'string', line 4, column 2 to column 17)",
  " (in 'string', line 5, column 9 to column 10)",
  " (in 'string', line 5, column 12 to column 13)",
  " (in 'string', line 5, column 2 to column 17)",
  " (in 'string', line 6, column 2 to column 19)",
  " (in 'string', line 7, column 2 to column 19)",
  " (in 'string', line 8, column 8 to column 9)",
  " (in 'string', line 8, column 2 to column 28)",
  " (in 'string', line 9, column 9 to column 10)",
  " (in 'string', line 9, column 12 to column 15)",
  " (in 'string', line 9, column 2 to column 21)",
  " (in 'string', line 11, column 9 to column 10)",
  " (in 'string', line 11, column 2 to column 19)",
  " (in 'string', line 12, column 9 to column 10)",
  " (in 'string', line 12, column 12 to column 13)",
  " (in 'string', line 12, column 2 to column 23)",
  " (in 'string', line 13, column 2 to column 16)",
  " (in 'string', line 14, column 2 to column 14)",
  " (in 'string', line 15, column 2 to column 17)",
  " (in 'string', line 18, column 9 to column 10)",
  " (in 'string', line 20, column 9 to column 12)",
  " (in 'string', line 21, column 9 to column 12)",
  " (in 'string', line 21, column 14 to column 17)",
  " (in 'string', line 22, column 23 to column 26)",
  " (in 'string', line 25, column 9 to column 12)",
  " (in 'string', line 26, column 9 to column 12)",
  " (in 'string', line 26, column 14 to column 17)"};
#include <stan_meta_header.hpp>
class model_nmr_model final : public model_base_crtp<model_nmr_model> {
private:
  int N;
  Eigen::Matrix<double,-1,1> Y_data__;
  int K;
  Eigen::Matrix<double,-1,-1> X_data__;
  int N_1;
  int M_1;
  std::vector<int> J_1;
  Eigen::Matrix<double,-1,-1> Z_1_data__;
  Eigen::Matrix<double,-1,1> b_mean_data__;
  Eigen::Matrix<double,-1,-1> b_sigma_data__;
  double psi_mean;
  double psi_sd;
  double lkj_shape;
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Z_1{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> b_mean{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> b_sigma{nullptr, 0, 0};
public:
  ~model_nmr_model() {}
  model_nmr_model(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_nmr_model_namespace::model_nmr_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 20;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 20;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("Y", "N", N);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "Y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&Y) Eigen::Map<Eigen::Matrix<double,-1,1>>(Y_data__.data(), N);
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 22;
        Y_flat__ = context__.vals_r("Y");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 22;
          stan::model::assign(Y, Y_flat__[(pos__ - 1)],
            "assigning variable Y", stan::model::index_uni(sym1__));
          current_statement__ = 22;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 23;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 23;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("X", "K", K);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, K);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 26;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 26;
        pos__ = 1;
        current_statement__ = 26;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 26;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 26;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 26;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 27;
      context__.validate_dims("data initialization", "N_1", "int",
        std::vector<size_t>{});
      N_1 = std::numeric_limits<int>::min();
      current_statement__ = 27;
      N_1 = context__.vals_i("N_1")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "N_1", N_1, 1);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "M_1", "int",
        std::vector<size_t>{});
      M_1 = std::numeric_limits<int>::min();
      current_statement__ = 28;
      M_1 = context__.vals_i("M_1")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "M_1", M_1, 1);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("J_1", "N", N);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "J_1", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      J_1 = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 30;
      J_1 = context__.vals_i("J_1");
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "J_1", J_1, 1);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("Z_1", "N", N);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("Z_1", "M_1", M_1);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "Z_1", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(M_1)});
      Z_1_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, M_1,
                     std::numeric_limits<double>::quiet_NaN());
      new (&Z_1) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Z_1_data__.data(),
        N, M_1);
      {
        std::vector<local_scalar_t__> Z_1_flat__;
        current_statement__ = 33;
        Z_1_flat__ = context__.vals_r("Z_1");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
          current_statement__ = 33;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 33;
            stan::model::assign(Z_1, Z_1_flat__[(pos__ - 1)],
              "assigning variable Z_1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 33;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 34;
      stan::math::validate_non_negative_index("b_mean", "K", K);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "b_mean", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      b_mean_data__ = Eigen::Matrix<double,-1,1>::Constant(K,
                        std::numeric_limits<double>::quiet_NaN());
      new (&b_mean)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(b_mean_data__.data(), K);
      {
        std::vector<local_scalar_t__> b_mean_flat__;
        current_statement__ = 35;
        b_mean_flat__ = context__.vals_r("b_mean");
        current_statement__ = 35;
        pos__ = 1;
        current_statement__ = 35;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 35;
          stan::model::assign(b_mean, b_mean_flat__[(pos__ - 1)],
            "assigning variable b_mean", stan::model::index_uni(sym1__));
          current_statement__ = 35;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 36;
      stan::math::validate_non_negative_index("b_sigma", "K", K);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("b_sigma", "K", K);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "b_sigma", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(K)});
      b_sigma_data__ = Eigen::Matrix<double,-1,-1>::Constant(K, K,
                         std::numeric_limits<double>::quiet_NaN());
      new (&b_sigma)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(b_sigma_data__.data(), K, K);
      {
        std::vector<local_scalar_t__> b_sigma_flat__;
        current_statement__ = 38;
        b_sigma_flat__ = context__.vals_r("b_sigma");
        current_statement__ = 38;
        pos__ = 1;
        current_statement__ = 38;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 38;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 38;
            stan::model::assign(b_sigma, b_sigma_flat__[(pos__ - 1)],
              "assigning variable b_sigma", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 38;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 39;
      context__.validate_dims("data initialization", "psi_mean", "double",
        std::vector<size_t>{});
      psi_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 39;
      psi_mean = context__.vals_r("psi_mean")[(1 - 1)];
      current_statement__ = 40;
      context__.validate_dims("data initialization", "psi_sd", "double",
        std::vector<size_t>{});
      psi_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 40;
      psi_sd = context__.vals_r("psi_sd")[(1 - 1)];
      current_statement__ = 41;
      context__.validate_dims("data initialization", "lkj_shape", "double",
        std::vector<size_t>{});
      lkj_shape = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 41;
      lkj_shape = context__.vals_r("lkj_shape")[(1 - 1)];
      current_statement__ = 42;
      stan::math::validate_non_negative_index("b", "K", K);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("psi", "M_1", M_1);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("z_1", "M_1", M_1);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("z_1", "N_1", N_1);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("L_1", "M_1", M_1);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("L_1", "M_1", M_1);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("lambda", "M_1", M_1);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("r_1", "N_1", N_1);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("r_1", "M_1", M_1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K + 1 + M_1 + (M_1 * N_1) + ((M_1 * (M_1 - 1)) / 2);
  }
  inline std::string model_name() const final {
    return "model_nmr_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_nmr_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> b =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      b = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> psi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M_1, DUMMY_VAR__);
      current_statement__ = 3;
      psi = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(M_1);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(M_1, N_1,
          DUMMY_VAR__);
      current_statement__ = 4;
      z_1 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(M_1,
              N_1);
      Eigen::Matrix<local_scalar_t__,-1,-1> L_1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(M_1, M_1,
          DUMMY_VAR__);
      current_statement__ = 5;
      L_1 = in__.template read_constrain_cholesky_factor_corr<
              Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(lp__, M_1);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M_1, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(lambda, stan::math::exp(psi),
        "assigning variable lambda");
      Eigen::Matrix<local_scalar_t__,-1,-1> r_1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_1, M_1,
          DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(r_1,
        stan::math::transpose(
          stan::math::multiply(
            stan::math::diag_pre_multiply(
              stan::math::multiply(lambda, sigma), L_1), z_1)),
        "assigning variable r_1");
      {
        current_statement__ = 9;
        stan::math::validate_non_negative_index("mu", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> mu =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 10;
        stan::model::assign(mu, stan::math::multiply(X, b),
          "assigning variable mu");
        current_statement__ = 13;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 11;
          stan::model::assign(mu,
            (stan::model::rvalue(mu, "mu", stan::model::index_uni(n)) +
            stan::math::dot_product(
              stan::model::rvalue(r_1, "r_1",
                stan::model::index_uni(
                  stan::model::rvalue(J_1, "J_1", stan::model::index_uni(n)))),
              stan::model::rvalue(Z_1, "Z_1", stan::model::index_uni(n)))),
            "assigning variable mu", stan::model::index_uni(n));
        }
        current_statement__ = 14;
        lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(b, b_mean,
                         b_sigma));
        current_statement__ = 15;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(sigma, 3, 0, 2.5));
        current_statement__ = 16;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(psi, psi_mean,
                         psi_sd));
        current_statement__ = 17;
        lp_accum__.add(stan::math::lkj_corr_cholesky_lpdf<propto__>(L_1,
                         lkj_shape));
        current_statement__ = 18;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                         stan::math::to_vector(z_1)));
        current_statement__ = 19;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(Y, mu, sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_nmr_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> b =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      b = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> psi =
        Eigen::Matrix<double,-1,1>::Constant(M_1,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      psi = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(M_1);
      Eigen::Matrix<double,-1,-1> z_1 =
        Eigen::Matrix<double,-1,-1>::Constant(M_1, N_1,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      z_1 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(M_1,
              N_1);
      Eigen::Matrix<double,-1,-1> L_1 =
        Eigen::Matrix<double,-1,-1>::Constant(M_1, M_1,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      L_1 = in__.template read_constrain_cholesky_factor_corr<
              Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(lp__, M_1);
      Eigen::Matrix<double,-1,1> lambda =
        Eigen::Matrix<double,-1,1>::Constant(M_1,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> r_1 =
        Eigen::Matrix<double,-1,-1>::Constant(N_1, M_1,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(b);
      out__.write(sigma);
      out__.write(psi);
      out__.write(z_1);
      out__.write(L_1);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 6;
      stan::model::assign(lambda, stan::math::exp(psi),
        "assigning variable lambda");
      current_statement__ = 8;
      stan::model::assign(r_1,
        stan::math::transpose(
          stan::math::multiply(
            stan::math::diag_pre_multiply(
              stan::math::multiply(lambda, sigma), L_1), z_1)),
        "assigning variable r_1");
      if (emit_transformed_parameters__) {
        out__.write(lambda);
        out__.write(r_1);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> b =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(b,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable b");
      out__.write(b);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
      Eigen::Matrix<local_scalar_t__,-1,1> psi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M_1, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(psi,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(M_1),
        "assigning variable psi");
      out__.write(psi);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(M_1, N_1,
          DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(z_1,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(M_1, N_1),
        "assigning variable z_1");
      out__.write(z_1);
      Eigen::Matrix<local_scalar_t__,-1,-1> L_1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(M_1, M_1,
          DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(L_1,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(M_1, M_1),
        "assigning variable L_1");
      out__.write_free_cholesky_factor_corr(L_1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "b", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "psi", "double",
        std::vector<size_t>{static_cast<size_t>(M_1)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "z_1", "double",
        std::vector<size_t>{static_cast<size_t>(M_1),
          static_cast<size_t>(N_1)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "L_1", "double",
        std::vector<size_t>{static_cast<size_t>(M_1),
          static_cast<size_t>(M_1)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> b =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> b_flat__;
        current_statement__ = 1;
        b_flat__ = context__.vals_r("b");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(b, b_flat__[(pos__ - 1)],
            "assigning variable b", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(b);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
      Eigen::Matrix<local_scalar_t__,-1,1> psi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M_1, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> psi_flat__;
        current_statement__ = 3;
        psi_flat__ = context__.vals_r("psi");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(psi, psi_flat__[(pos__ - 1)],
            "assigning variable psi", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(psi);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(M_1, N_1,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_1_flat__;
        current_statement__ = 4;
        z_1_flat__ = context__.vals_r("z_1");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= N_1; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= M_1; ++sym2__) {
            current_statement__ = 4;
            stan::model::assign(z_1, z_1_flat__[(pos__ - 1)],
              "assigning variable z_1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 4;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(z_1);
      Eigen::Matrix<local_scalar_t__,-1,-1> L_1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(M_1, M_1,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> L_1_flat__;
        current_statement__ = 5;
        L_1_flat__ = context__.vals_r("L_1");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
          current_statement__ = 5;
          for (int sym2__ = 1; sym2__ <= M_1; ++sym2__) {
            current_statement__ = 5;
            stan::model::assign(L_1, L_1_flat__[(pos__ - 1)],
              "assigning variable L_1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 5;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_cholesky_factor_corr(L_1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"b", "sigma", "psi", "z_1", "L_1"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"lambda", "r_1"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(M_1)},
                std::vector<size_t>{static_cast<size_t>(M_1),
                  static_cast<size_t>(N_1)},
                std::vector<size_t>{static_cast<size_t>(M_1),
                  static_cast<size_t>(M_1)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(M_1)},
             std::vector<size_t>{static_cast<size_t>(N_1),
               static_cast<size_t>(M_1)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "b" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma");
    for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
      param_names__.emplace_back(std::string() + "psi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_1; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= M_1; ++sym2__) {
        param_names__.emplace_back(std::string() + "z_1" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= M_1; ++sym2__) {
        param_names__.emplace_back(std::string() + "L_1" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
        param_names__.emplace_back(std::string() + "lambda" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_1; ++sym2__) {
          param_names__.emplace_back(std::string() + "r_1" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "b" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma");
    for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
      param_names__.emplace_back(std::string() + "psi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_1; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= M_1; ++sym2__) {
        param_names__.emplace_back(std::string() + "z_1" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= ((M_1 * (M_1 - 1)) / 2); ++sym1__) {
      param_names__.emplace_back(std::string() + "L_1" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
        param_names__.emplace_back(std::string() + "lambda" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= M_1; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_1; ++sym2__) {
          param_names__.emplace_back(std::string() + "r_1" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"psi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M_1) + "},\"block\":\"parameters\"},{\"name\":\"z_1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(M_1) + ",\"cols\":" + std::to_string(N_1) + "},\"block\":\"parameters\"},{\"name\":\"L_1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(M_1) + ",\"cols\":" + std::to_string(M_1) + "},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M_1) + "},\"block\":\"transformed_parameters\"},{\"name\":\"r_1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_1) + ",\"cols\":" + std::to_string(M_1) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"psi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M_1) + "},\"block\":\"parameters\"},{\"name\":\"z_1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(M_1) + ",\"cols\":" + std::to_string(N_1) + "},\"block\":\"parameters\"},{\"name\":\"L_1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(((M_1 * (M_1 - 1)) /2)) + "},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M_1) + "},\"block\":\"transformed_parameters\"},{\"name\":\"r_1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_1) + ",\"cols\":" + std::to_string(M_1) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((K + 1) + M_1) + (M_1 * N_1)) + (M_1 *
      M_1));
    const size_t num_transformed = emit_transformed_parameters * ((M_1 + (N_1
      * M_1)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((K + 1) + M_1) + (M_1 * N_1)) + (M_1 *
      M_1));
    const size_t num_transformed = emit_transformed_parameters * ((M_1 + (N_1
      * M_1)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_nmr_model_namespace::model_nmr_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_nmr_model_namespace::profiles__;
}
#endif
#endif
