// Generated by rstantools.  Do not edit by hand.

/*
    nafm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    nafm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with nafm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_iv_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 46> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 18, column 2 to column 17)",
  " (in 'string', line 19, column 2 to column 19)",
  " (in 'string', line 20, column 2 to column 30)",
  " (in 'string', line 21, column 2 to column 33)",
  " (in 'string', line 24, column 2 to column 24)",
  " (in 'string', line 27, column 9 to column 10)",
  " (in 'string', line 27, column 12 to column 13)",
  " (in 'string', line 27, column 2 to column 51)",
  " (in 'string', line 28, column 9 to column 10)",
  " (in 'string', line 28, column 12 to column 13)",
  " (in 'string', line 28, column 2 to column 35)",
  " (in 'string', line 29, column 9 to column 10)",
  " (in 'string', line 29, column 12 to column 13)",
  " (in 'string', line 29, column 2 to column 41)",
  " (in 'string', line 32, column 9 to column 10)",
  " (in 'string', line 32, column 2 to column 56)",
  " (in 'string', line 34, column 2 to column 39)",
  " (in 'string', line 35, column 2 to column 37)",
  " (in 'string', line 36, column 2 to column 33)",
  " (in 'string', line 37, column 2 to column 42)",
  " (in 'string', line 39, column 2 to column 35)",
  " (in 'string', line 40, column 2 to column 38)",
  " (in 'string', line 42, column 2 to column 29)",
  " (in 'string', line 2, column 2 to column 17)",
  " (in 'string', line 3, column 2 to column 17)",
  " (in 'string', line 4, column 9 to column 10)",
  " (in 'string', line 4, column 2 to column 14)",
  " (in 'string', line 5, column 9 to column 10)",
  " (in 'string', line 5, column 12 to column 13)",
  " (in 'string', line 5, column 2 to column 17)",
  " (in 'string', line 6, column 9 to column 10)",
  " (in 'string', line 6, column 12 to column 13)",
  " (in 'string', line 6, column 2 to column 17)",
  " (in 'string', line 8, column 9 to column 10)",
  " (in 'string', line 8, column 2 to column 19)",
  " (in 'string', line 9, column 9 to column 10)",
  " (in 'string', line 9, column 12 to column 13)",
  " (in 'string', line 9, column 2 to column 23)",
  " (in 'string', line 10, column 2 to column 16)",
  " (in 'string', line 11, column 2 to column 16)",
  " (in 'string', line 12, column 2 to column 16)",
  " (in 'string', line 13, column 2 to column 14)",
  " (in 'string', line 14, column 2 to column 19)",
  " (in 'string', line 15, column 2 to column 17)",
  " (in 'string', line 18, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_iv_model final : public model_base_crtp<model_iv_model> {
private:
  int N;
  int K;
  Eigen::Matrix<double,-1,1> y_data__;
  Eigen::Matrix<double,-1,-1> X_data__;
  Eigen::Matrix<double,-1,-1> A_data__;
  Eigen::Matrix<double,-1,1> b_mean_data__;
  Eigen::Matrix<double,-1,-1> b_sigma_data__;
  double s2_shape;
  double s2_scale;
  double rho_mean;
  double rho_sd;
  double lambda_mean;
  double lambda_sd;
  Eigen::Map<Eigen::Matrix<double,-1,1>> y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> A{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> b_mean{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> b_sigma{nullptr, 0, 0};
public:
  ~model_iv_model() {}
  model_iv_model(stan::io::var_context& context__, unsigned int
                 random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_iv_model_namespace::model_iv_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 24;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 24;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 25;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "K", K, 0);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      y_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double,-1,1>>(y_data__.data(), N);
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 27;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 27;
        pos__ = 1;
        current_statement__ = 27;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 27;
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          current_statement__ = 27;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 28;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("X", "K", K);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, K);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 30;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 30;
        pos__ = 1;
        current_statement__ = 30;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 30;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 30;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 30;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 31;
      stan::math::validate_non_negative_index("A", "N", N);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("A", "N", N);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "A", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(N)});
      A_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&A) Eigen::Map<Eigen::Matrix<double,-1,-1>>(A_data__.data(), N, N);
      {
        std::vector<local_scalar_t__> A_flat__;
        current_statement__ = 33;
        A_flat__ = context__.vals_r("A");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 33;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 33;
            stan::model::assign(A, A_flat__[(pos__ - 1)],
              "assigning variable A", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 33;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 34;
      stan::math::validate_non_negative_index("b_mean", "K", K);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "b_mean", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      b_mean_data__ = Eigen::Matrix<double,-1,1>::Constant(K,
                        std::numeric_limits<double>::quiet_NaN());
      new (&b_mean)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(b_mean_data__.data(), K);
      {
        std::vector<local_scalar_t__> b_mean_flat__;
        current_statement__ = 35;
        b_mean_flat__ = context__.vals_r("b_mean");
        current_statement__ = 35;
        pos__ = 1;
        current_statement__ = 35;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 35;
          stan::model::assign(b_mean, b_mean_flat__[(pos__ - 1)],
            "assigning variable b_mean", stan::model::index_uni(sym1__));
          current_statement__ = 35;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 36;
      stan::math::validate_non_negative_index("b_sigma", "K", K);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("b_sigma", "K", K);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "b_sigma", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(K)});
      b_sigma_data__ = Eigen::Matrix<double,-1,-1>::Constant(K, K,
                         std::numeric_limits<double>::quiet_NaN());
      new (&b_sigma)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(b_sigma_data__.data(), K, K);
      {
        std::vector<local_scalar_t__> b_sigma_flat__;
        current_statement__ = 38;
        b_sigma_flat__ = context__.vals_r("b_sigma");
        current_statement__ = 38;
        pos__ = 1;
        current_statement__ = 38;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 38;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 38;
            stan::model::assign(b_sigma, b_sigma_flat__[(pos__ - 1)],
              "assigning variable b_sigma", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 38;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 39;
      context__.validate_dims("data initialization", "s2_shape", "double",
        std::vector<size_t>{});
      s2_shape = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 39;
      s2_shape = context__.vals_r("s2_shape")[(1 - 1)];
      current_statement__ = 40;
      context__.validate_dims("data initialization", "s2_scale", "double",
        std::vector<size_t>{});
      s2_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 40;
      s2_scale = context__.vals_r("s2_scale")[(1 - 1)];
      current_statement__ = 41;
      context__.validate_dims("data initialization", "rho_mean", "double",
        std::vector<size_t>{});
      rho_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 41;
      rho_mean = context__.vals_r("rho_mean")[(1 - 1)];
      current_statement__ = 42;
      context__.validate_dims("data initialization", "rho_sd", "double",
        std::vector<size_t>{});
      rho_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 42;
      rho_sd = context__.vals_r("rho_sd")[(1 - 1)];
      current_statement__ = 43;
      context__.validate_dims("data initialization", "lambda_mean", "double",
        std::vector<size_t>{});
      lambda_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 43;
      lambda_mean = context__.vals_r("lambda_mean")[(1 - 1)];
      current_statement__ = 44;
      context__.validate_dims("data initialization", "lambda_sd", "double",
        std::vector<size_t>{});
      lambda_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 44;
      lambda_sd = context__.vals_r("lambda_sd")[(1 - 1)];
      current_statement__ = 45;
      stan::math::validate_non_negative_index("beta", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_iv_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_iv_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      local_scalar_t__ s2 = DUMMY_VAR__;
      current_statement__ = 2;
      s2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 3;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 4;
      lambda = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(-1, 1, lp__);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 5;
      sigma = stan::math::sqrt(s2);
      {
        current_statement__ = 6;
        stan::math::validate_non_negative_index("I", "N", N);
        current_statement__ = 7;
        stan::math::validate_non_negative_index("I", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,-1> I =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
        current_statement__ = 8;
        stan::model::assign(I,
          stan::math::diag_matrix(stan::math::rep_vector(1.0, N)),
          "assigning variable I");
        current_statement__ = 9;
        stan::math::validate_non_negative_index("W_rho", "N", N);
        current_statement__ = 10;
        stan::math::validate_non_negative_index("W_rho", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,-1> W_rho =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
        current_statement__ = 11;
        stan::model::assign(W_rho,
          stan::math::subtract(I, stan::math::multiply(rho, A)),
          "assigning variable W_rho");
        current_statement__ = 12;
        stan::math::validate_non_negative_index("W_lambda", "N", N);
        current_statement__ = 13;
        stan::math::validate_non_negative_index("W_lambda", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,-1> W_lambda =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
        current_statement__ = 14;
        stan::model::assign(W_lambda,
          stan::math::subtract(I, stan::math::multiply(lambda, A)),
          "assigning variable W_lambda");
        current_statement__ = 15;
        stan::math::validate_non_negative_index("epsilon", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> epsilon =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 16;
        stan::model::assign(epsilon,
          stan::math::multiply(W_lambda,
            stan::math::subtract(stan::math::multiply(W_rho, y),
              stan::math::multiply(X, beta))), "assigning variable epsilon");
        current_statement__ = 17;
        lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(beta, b_mean,
                         b_sigma));
        current_statement__ = 18;
        lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(s2, s2_shape,
                         s2_scale));
        current_statement__ = 19;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(rho, rho_mean,
                         rho_sd));
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(lambda, lambda_mean,
                         lambda_sd));
        current_statement__ = 21;
        lp_accum__.add(stan::math::log_determinant(W_rho));
        current_statement__ = 22;
        lp_accum__.add(stan::math::log_determinant(W_lambda));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(epsilon, 0, sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_iv_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      double s2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      s2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      double rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      double lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      lambda = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(-1, 1, lp__);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      out__.write(beta);
      out__.write(s2);
      out__.write(rho);
      out__.write(lambda);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 5;
      sigma = stan::math::sqrt(s2);
      if (emit_transformed_parameters__) {
        out__.write(sigma);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable beta");
      out__.write(beta);
      local_scalar_t__ s2 = DUMMY_VAR__;
      current_statement__ = 2;
      s2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s2);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 3;
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lub(-1, 1, rho);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 4;
      lambda = in__.read<local_scalar_t__>();
      out__.write_free_lub(-1, 1, lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "s2", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "rho", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "lambda", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      local_scalar_t__ s2 = DUMMY_VAR__;
      current_statement__ = 2;
      s2 = context__.vals_r("s2")[(1 - 1)];
      out__.write_free_lb(0, s2);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 3;
      rho = context__.vals_r("rho")[(1 - 1)];
      out__.write_free_lub(-1, 1, rho);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 4;
      lambda = context__.vals_r("lambda")[(1 - 1)];
      out__.write_free_lub(-1, 1, lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta", "s2", "rho", "lambda"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"sigma"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s2");
    param_names__.emplace_back(std::string() + "rho");
    param_names__.emplace_back(std::string() + "lambda");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "sigma");
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s2");
    param_names__.emplace_back(std::string() + "rho");
    param_names__.emplace_back(std::string() + "lambda");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "sigma");
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"s2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"s2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_iv_model_namespace::model_iv_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_iv_model_namespace::profiles__;
}
#endif
#endif
